// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsineAPI.Data;

namespace UsineAPI.Migrations
{
    [DbContext(typeof(UsineAPIContext))]
    [Migration("20191222124520_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UsineAPI.Models.ChefEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("Id");

                    b.ToTable("ChefEquipe");
                });

            modelBuilder.Entity("UsineAPI.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChefEquipeId");

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.Property<int>("RoleID");

                    b.HasKey("Id");

                    b.HasIndex("ChefEquipeId");

                    b.HasIndex("RoleID");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("UsineAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomRole");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("UsineAPI.Models.SuperUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("MotDePasse");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("Id");

                    b.ToTable("SuperUser");
                });

            modelBuilder.Entity("UsineAPI.Models.Employe", b =>
                {
                    b.HasOne("UsineAPI.Models.ChefEquipe")
                        .WithMany("Employes")
                        .HasForeignKey("ChefEquipeId");

                    b.HasOne("UsineAPI.Models.Role", "Role")
                        .WithMany("Employes")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
